---
  - name: vm db
    hosts: db
    become: true
    vars:
        mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
    tasks:
    - name: Изменить конфигурацию mongo
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

    handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

