---
  - name: Configure hosts & deploy application
    hosts: all
    vars:
        mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
        db_host: 10.128.0.5 # <-- подставьте сюда ваш IP
    tasks:
    - name: Установка Git
      become: true
      apt:
        name: git
        state: present
      tags: app-tag

    - name: Изменить конфигурацию mongo
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag # <-- Список тэгов для задачи
      notify: restart mongod

    - name: Добавить сервис для Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag

    - name: Перезапуск systemd-daemon
      become: true
      systemd:
        daemon_reload: yes
      tags: app-tag

    - name: enable Puma (systemctl daemon-reload если не работает)
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Добавление конфига для DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: Добавление последней версии reddit
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: установка Bundle
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag

    handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
