---
  - name: vm db
    hosts: db
    tags: db-tag
    become: true
    vars:
        mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
    tasks:
    - name: Изменить конфигурацию mongo
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

    handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

  - name: vm app
    hosts: app
    tags: app-tag
    become: true
    vars:
        db_host: 10.128.0.14 # <-- подставьте сюда ваш IP
    tasks:
    - name: Добавить сервис для Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Перезапуск systemd-daemon
      systemd:
        daemon_reload: yes

    - name: Добавление конфига для DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable Puma
      systemd: name=puma enabled=yes

    handlers: # <-- Добавим блок handlers и задачу
    - name: reload puma
      become: true
      systemd: name=puma state=restarted

  - name: vm app deploy apply
    hosts: app
    tags: deploy-tag
    become: true

    tasks:
    - name: Установка Git
      apt:
        name: git
        state: present

    - name: Добавление последней версии reddit
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: установка Bundle
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle

    handlers: # <-- Добавим блок handlers и задачу
    - name: reload puma
      become: true
      systemd: name=puma state=restarted

